export const songs = [
    { Year: 2023, Song: 'Flowers', Artist: 'Miley Cyrus', YouTube_Link: 'https://www.youtube.com/watch?v=G7KNmW9a75Y',Song2:'what I was made for',Artist2:'Billie Eilish' , YouTube_Link2:'https://www.youtube.com/watch?v=cW8VLC9nnTo'},
    { Year: 2022, Song: 'Heat Waves', Artist: 'Glass Animals', YouTube_Link: 'https://www.youtube.com/watch?v=mRD0-GxqHVo',Song2:'as it was',Artist2:'harry styles', YouTube_Link2: 'https://www.youtube.com/watch?v=Qfm6nfz1QNQ' },
    { Year: 2021, Song: 'Levitating', Artist: 'Dua Lipa', YouTube_Link: 'https://www.youtube.com/watch?v=TUVcZfQe-Kw',Song2:'save your tears ',Artist2:'the weekend' ,YouTube_Link2 : 'https://www.youtube.com/watch?v=u6lihZAcy4s' },
    { Year: 2020, Song: 'Blinding Lights', Artist: 'The Weeknd', YouTube_Link: 'https://www.youtube.com/watch?v=fHI8X4OXluQ', Song2:'Circles', Artist2:'Post Malone', YouTube_Link2: 'https://www.youtube.com/watch?v=wXhTHyIgQ_U' },
    { Year: 2019, Song: 'Old Town Road', Artist: 'Lil Nas X', YouTube_Link: 'https://www.youtube.com/watch?v=r7qovpFAGrQ', Song2:'sunflower' ,Artist2:'Post Malone', YouTube_Link2: 'https://www.youtube.com/watch?v=ApXoWvfEYVU' },
    { Year: 2018, Song: "havana", Artist: 'Camila Cabello ', YouTube_Link: 'https://www.youtube.com/watch?v=HCjNJDNzw8Y',Song2:'perfect',Artist2 : 'Ed Sheeran', YouTube_Link2: 'https://www.youtube.com/watch?v=2Vv-BfVoq4g' },
    { Year: 2017, Song: 'Shape of You', Artist: 'Ed Sheeran', YouTube_Link: 'https://www.youtube.com/watch?v=JGwWNGJdvx8', Song2:'something just like this',Artist2:'The Chainsmokers and coldplay', YouTube_Link2: 'https://www.youtube.com/watch?v=FM7MFYoylVs' },
    { Year: 2016, Song: 'Love Yourself', Artist: 'Justin Bieber', YouTube_Link: 'https://www.youtube.com/watch?v=oyEuk8j8imI',Song2:'Stressed Out', Artist2:'Twenty One Pilots', YouTube_Link2: 'https://www.youtube.com/watch?v=pXRviuL6vMY' },
    { Year: 2015, Song: 'Uptown Funk', Artist: 'Mark Ronson featuring Bruno Mars', YouTube_Link: 'https://www.youtube.com/watch?v=OPf0YbXqDm0',Song2 :'sugar' ,Artist2:'maroon 5', YouTube_Link2: 'https://www.youtube.com/watch?v=09R8_2nJtjg' },
    { Year: 2014, Song: 'Happy', Artist: 'Pharrell Williams', YouTube_Link: 'https://www.youtube.com/watch?v=ZbZSe6N_BXs', Song2 : 'Dark horse',Artist2:'katy perry', YouTube_Link2:'https://www.youtube.com/watch?v=0KSOMA3QBU0'},
    { Year: 2013, Song: 'Thrift Shop', Artist: 'Macklemore and Ryan Lewis featuring Wanz', YouTube_Link: 'https://www.youtube.com/watch?v=QK8mJJJvaes', Song2:'radioactive', artist2:'Imagine Drgons',YouTube_Link2:'https://www.youtube.com/watch?v=w3viBe2Q0P8'},
    { Year: 2012, Song: 'Somebody That I Used to Know', Artist: 'Gotye featuring Kimbra', YouTube_Link: 'https://www.youtube.com/watch?v=8UVNT4wvIGY',Song2:'we are young',artist2:'fun, ft. Janelle Monáe', YouTube_Link2: 'https://www.youtube.com/watch?v=Sv6dMFF_yts'},
    { Year: 2011, Song: 'Rolling in the Deep', Artist: 'Adele', YouTube_Link: 'https://www.youtube.com/watch?v=rYEDA3JcQqw', song2:'Firework', artist2:'Katy Perry', YouTube_Link2 :'https://www.youtube.com/watch?v=QGJuMBdaqIw' },
    { Year: 2010, Song: 'Tik Tok', Artist: 'Kesha', YouTube_Link: 'https://www.youtube.com/watch?v=iP6XpLQM2Cs', song2:'hey soul sister',artist2:'train',YouTube_Link2 :'https://www.youtube.com/watch?v=kVpv8-5XWOI'  },
    { Year: 2009, Song: 'I gotta a feeling', Artist: 'The Black Eyed Peas', YouTube_Link: 'https://www.youtube.com/watch?v=ipii7KbbJLY' },
    { Year: 2008, Song: 'Apologize', Artist: 'One Republic ', YouTube_Link: 'https://www.youtube.com/watch?v=q6i3LgOjyGY' },
    { Year: 2007, Song: 'Irreplaceable', Artist: 'Beyoncé', YouTube_Link: 'https://www.youtube.com/watch?v=2EwViQxSJJQ', Song2:'umberlla',Artist2:'Rihanna', YouTube_Link2: 'https://www.youtube.com/watch?v=CvBfHwUxHIk' },
    { Year: 2006, Song: 'Bad Day', Artist: 'Daniel Powter', YouTube_Link: 'https://www.youtube.com/watch?v=gH476CxJxfg' },
    { Year: 2005, Song: 'Boulevard of Broken Dreams', Artist: 'Green Day ', YouTube_Link: 'https://www.youtube.com/watch?v=gYCTXzOTnXg' },
    { Year: 2004, Song: 'Yeah!', Artist: 'Usher featuring Lil Jon and Ludacris', YouTube_Link: 'https://www.youtube.com/watch?v=GxBSyx85Kp8' },
    { Year: 2003, Song: 'Ignition', Artist: 'R. Kelly ', YouTube_Link: 'https://www.youtube.com/watch?v=lCPdtMbw7zg' },
    { Year: 2002, Song: 'How You Remind Me', Artist: 'Nickelback', YouTube_Link: 'https://www.youtube.com/watch?v=1cQh1ccqu8M' },
    { Year: 2001, Song: 'Drops of Jupiter', Artist: 'Train', YouTube_Link: 'https://www.youtube.com/watch?v=pXYc_9tToio' },
    { Year: 2000, Song: 'smooth', Artist: 'Rob Thomas', YouTube_Link: 'https://www.youtube.com/watch?v=guG1JbozB2E' },
    { Year: 1999, Song: 'Believe', Artist: 'Cher', YouTube_Link: 'https://www.youtube.com/watch?v=nZXRV4MezEw' },
    { Year: 1998, Song: 'Too Close', Artist: 'Next', YouTube_Link: 'https://www.youtube.com/watch?v=kwEZRPkAAu8' },
    { Year: 1997, Song: 'Candle in the Wind 1997', Artist: 'Elton John', YouTube_Link: 'https://www.youtube.com/watch?v=QPxcIZpRuOE' },
    { Year: 1996, Song: 'One Sweet Day ', Artist: 'Mariah Carey, Boyz II Men', YouTube_Link: 'https://www.youtube.com/watch?v=UXxRyNvTPr8' },
    { Year: 1995, Song: 'waterfalls', Artist: 'TLC', YouTube_Link: 'https://www.youtube.com/watch?v=8WEtxJ4-sh4' },
    { Year: 1994, Song: 'The Sign', Artist: 'Ace of Base', YouTube_Link: 'https://www.youtube.com/watch?v=iqu132vTl5Y' },
    { Year: 1993, Song: 'I Will Always Love You', Artist: 'Whitney Houston', YouTube_Link: 'https://www.youtube.com/watch?v=3JWTaaS7LdU' },
    { Year: 1992, Song: 'End of the Road', Artist: 'Boyz II Men', YouTube_Link: 'https://www.youtube.com/watch?v=zDKO6XYXioc' },
    { Year: 1991, Song: 'Everything I Do (I Do It for You)', Artist: 'Bryan Adams', YouTube_Link: 'https://www.youtube.com/watch?v=Y0pdQU87dc8' },
    { Year: 1990, Song: 'nothing compares to U', Artist: 'Sinéad OConnor', YouTube_Link: 'https://www.youtube.com/watch?v=0-EF60neguk' },
    { Year: 1989, Song: 'Look Away', Artist: 'Chicago', YouTube_Link: 'https://www.youtube.com/watch?v=OsBkMGtLjIY' },
    { Year: 1988, Song: 'Faith', Artist: 'George Michael', YouTube_Link: 'https://www.youtube.com/watch?v=6Cs3Pvmmv0E' },
    { Year: 1987, Song: 'Walk Like an Egyptian', Artist: 'The Bangles', YouTube_Link: 'https://www.youtube.com/watch?v=Cv6tuzHUuuk' },
    { Year: 1986, Song: 'That\'s What Friends Are For', Artist: 'Dionne Warwick and Friends', YouTube_Link: 'https://www.youtube.com/watch?v=HyTpu6BmE88' },
    { Year: 1985, Song: 'Careless Whisper', Artist: 'Wham! featuring George Michael', YouTube_Link: 'https://www.youtube.com/watch?v=izGwDsrQ1eQ' },
    { Year: 1984, Song: 'When Doves Cry', Artist: 'Prince', YouTube_Link: 'https://www.youtube.com/watch?v=UG3VcCAlUgE' },
    { Year: 1983, Song: 'Every Breath You Take', Artist: 'The Police', YouTube_Link: 'https://www.youtube.com/watch?v=OMOGaugKpzs' },
    { Year: 1982, Song: 'Eye of The Tiger', Artist: 'Survivor', YouTube_Link: 'https://www.youtube.com/watch?v=btPJPFnesV4' },
    { Year: 1981, Song: ' Starting Over', Artist: 'John Lennon', YouTube_Link: 'https://www.youtube.com/watch?v=e6vllWj1idc' },
    {Year: 1980,Song: "Call Me",Artist: "Blondie",YouTube_Link: "https://www.youtube.com/watch?v=StKVS0eI85I"}
  ]
  